name: Core
version: 1.0
api-version: 1.18
softdepend: [PlaceholderAPI]
author: Sir_Blob_
website: "https://sirblob.bosstop.ml"
main: net.lglprison.Main
description: LGL Prisons Core plugin
load: STARTUP

commands:
  discord:
    aliases: [d]
    description: Discord Command
    usage: /discord connect | find
  pay:
    aliases: [pay]
    description: Pay Command
    usage: /pay
  economy:
    aliases: [ econ ]
    description: Economy Command
    usage: /econ
  me:
    aliases: [ me ]
    description: Me Command
    usage: /me

permissions:
  core.discord:
    default: op
  core.admin:
    default: op